### ISSUE TITLE
Persistency of signature + salt 

### ISSUE THREAD

**Issue by karimaboulenein** [alexbivz/unity3d-gamekit-identity-plugin#2]
Hello ! 

This is not really an issue but rather a question. Are the signature and salt persistent ? (do I need to refresh them at each session, or can I just save them locally once I got them the first time ?)

Thank you,

**Comment by ghost** [comment]
Yo, @karimlarge!

On each authenticate you must do this, because it's the confirmation of GameCenter Auth. For example GameSparks:
1. User have big dream to connect in your app with GameCenter;
2. Start `Social.localUser.Authenticate`;
3. Generate identity via plugin (for server side verification you its you);
4. Send GameSparks's `GameCenterConnectRequest` with our data from plugin;
5. Check response and do something.

You dont need store plugin data, because you already authenticated and your server verify you. 
Read [here](https://developer.apple.com/documentation/gamekit/gklocalplayer/1515407-generateidentityverificationsign?language=objc).

Good luck!

**Comment by karimaboulenein** [comment]
Hey Alex ! 

Thanks for your reply. 

So this means that just like a Facebook access token, these credentials will expire ?
My dream would be to have the player touching this Game Center button only once in his life (just for me to get the credentials), and then authenticating him on Gamesparks automatically with these credentials saved in my keychain (and skip all the Game Center Authentication + potential Gamesparks unsafe DeviceAuthentications)

**Comment by ghost** [comment]
Yo, @karimlarge !

**You have two ways:**

1. Login with GameCenter each app launch;
2. Only bind GameCenter and login with your own mechanism.

**For first:**

If user already log in to GameCenter, when your app call `Social.localUser.Authenticate` all actions doing in background and user only see the message like this `Welcome back, karimlarge`.

Just call `GameCenterConnectRequest` on each app startup.

New user created if not exists and returned if exists.

**For second:**

Auth user with your method (e.g. DeviceAuthenticationRequest). Check response socials data for contains GC account or not. If no - show button. On button click call `GameCenterConnectRequest`. This bind GC to already created account.

I mean this help you.

**Comment by ghost** [comment]
@karimlarge you must do authentication every session for get GameSparks access token. Access token will expire.

**Comment by karimaboulenein** [comment]
Thank you

Since iOS7, the deviceId is not fixed on the MAC address anymore and it changes upon reinstall. This is why we started doing some Game Center auth.
And we need to pre-authenticate the player with DeviceAuthenticationRequest, because there is some data we need from the server even if the player is not "really" authenticated (server timestamp to avoid cheating on countdowns, etc...).

On Android, it's cool. The deviceId is persistent, so are the Google Play credentials. But on iOS, everything requires extra work :) 
If the Game Center credentials are not persistent, I will make sure that the player is logged into Game Center at startup or each time I try to authenticate him, then fetch then, then call GameCenterConnectRequest.

Thanks for your help !

**Comment by ghost** [comment]
Yeah, @karimlarge, iOS it's hell :)

Yep, you right. I show you algorithm which i using, maybe this help you too:

Call `Social.localUser.Authenticate`...

**Success**
User already login to GameCenter or successfully login just now.
1. Call `GameCenterConnectRequest` and save as default login method;

**Error**
User not login to GameCenter and close auth popup (or iOS shity errors):
1. Call `DeviceAuthenticationRequest ` and save this as default login method **(if GameCenter login method NOT already setted)**;
2. Show in game GameCenter button **(if auth response not contains GC social connection)**;
3. If user click GC button and successfully login, change default method to login with GC (call `GameCenterConnectRequest` at startup).

**Comment by ghost** [comment]
You are welcome, @karimlarge !
